# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/MYP5',
                'doc_host': 'https://maya-guizzi.github.io',
                'git_url': 'https://github.com/maya-guizzi/MYP5',
                'lib_path': 'MYP5'},
  'syms': {'MYP5.core': {'MYP5.core.foo': ('core.html#foo', 'MYP5/core.py')}}}
